### ISSUE TITLE
Edge case in `tnmom2` 

### ISSUE THREAD

**Issue by suzannastep** [cossio/TruncatedNormal.jl#2]
For `tnmom2`  in the case of uniform distributions, if σ = 0 it returns `clamp(μ^2 / one(μ), a, b)`, which is μ^2 if μ^2 is in the truncation region, or else the nearest boundary. 

Should it instead return `clamp(μ/ one(μ), a, b)^2`, i.e. `μ^2` if *μ* is in the truncation region, or else the nearest boundary *squared*?

**Comment by cossio** [comment]
You are right, good catch!
