### ISSUE TITLE
Merge into Distributions.jl?

### ISSUE THREAD

**Issue by ParadaCarleton** [cossio/TruncatedNormal.jl#5]
Hi, is this any different from the Truncated Normal distribution in Distributions.jl? If so, are there any advantages to this approach that could be ported over to Distributions?

**Comment by cossio** [comment]
Already merged, see https://github.com/JuliaStats/Distributions.jl/pull/1058, https://github.com/JuliaStats/Distributions.jl/pull/691.

**Comment by ParadaCarleton** [comment]
Ahh, thank you! Could you mention this in the ReadMe?

**Comment by cossio** [comment]
@ParadaCarleton Done!
